version: "3.3"
services:
  fibonacci_service:
    build: .
    ports:
    - "8000:80"
    depends_on:
      - cache
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local